version: '3'
services:
  redis:
    image: redis:latest
  landing:
    image: fisherhall/landing:latest
    env_file:
      - ./.env.production
    command: java -jar target/landing-jar-with-dependencies.jar
    ports:
      - "4567:4567"
    depends_on:
      - redis

